// Copyright 2008-2013, 2017 Dennis Ferron

namespace Glue {

enum CUSTOM_ESCENE_NODE_ANIMATOR_TYPE
{
    C_ESNAT_SCRIPT_OBJ = 0x100,
    C_ESNAT_PHYSICAL,
    C_ESNAT_KINEMATIC,
    C_ESNAT_LOCK,

    CUSTOM_ESCENE_NODE_ANIMATOR_TYPE_FORCE_32_BIT = 0x7fffffffL
};

}
